urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("", views.index, name="index"),
    path("get_all_codes", views.get_all_codes, name="get_all_codes"),
    path("add_new_code", views.add_new_code, name="add_new_code"),
    path("", views.get_user_data, name="get_user_data"),
    path("get_all_redemptions", views.get_all_redemptions, name="get_all_redemptions"),
]

models.py
# pip install django-model-utils
# pip install django==2.0

from django.db import models

from django.contrib.auth.models import User, AbstractUser
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from model_utils.models import TimeStampedModel

from django.utils import timezone

# from django.utils.translation import ugettext_lazy as _


DISCOUNT_CHOICES = (("percentage", "Percentage"), ("flat", "Flat"))

GENDER_CHOICES = (("m", "Male"), ("f", "Female"))


class Coupon(TimeStampedModel):
    """
    This table contains coupon codes
    A user can get a discount offer on course if provide coupon code
    """

    class Meta(object):
        app_label = "promocode"

    code = models.CharField(
        max_length=32,
        help_text="Only uppercase letters & numbers are allowed.",
        validators=[
            RegexValidator(
                "^[A-Z0-9]*$", "Only uppercase letters & numbers are allowed."
            )
        ],
    )

    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)

    start_date = models.DateTimeField()
    expiration_date = models.DateTimeField()

    discount_type = models.CharField(max_length=32, choices=DISCOUNT_CHOICES)

    discount = models.PositiveIntegerField()

    max_discount_amout = models.PositiveIntegerField(
        help_text="This is max amount users will get after the promo code is applied."
    )

    number_of_uses = models.PositiveIntegerField(
        help_text="How many times this coupon will be used.", default=1
    )

    per_user_limit = models.PositiveIntegerField()

    is_active = models.BooleanField(default=True)

    # is_used = models.BooleanField(default=False)

    def __str__(self):
        return self.code

    def __enumerable_to_display(self, enumerables, enum_value):
        """Get the human readable value from an enumerable list of key-value pairs."""
        return dict(enumerables)[enum_value]

    @property
    def display_gender(self):
        """
        return coupon gender
        """
        return self.__enumerable_to_display(GENDER_CHOICES, self.gender)


class UserProfile(TimeStampedModel):
    user = models.OneToOneField(
        User,
        unique=True,
        db_index=True,
        related_name="profile",
        on_delete=models.CASCADE,
    )
    date_of_birth = models.DateField(blank=False, null=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)

    class Meta(object):
        app_label = "promocode"

    def __str__(self):
        return "{}".format(self.user.username)


class CouponRedemption(TimeStampedModel):
    """
    This table contain coupon redemption info
    """

    class Meta(object):
        app_label = "promocode"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    order_amount = models.PositiveIntegerField()
    actual_price = models.PositiveIntegerField(
        help_text="Order total amount after code redemption applied."
    )

    def __str__(self):
        return "{} - {}".format(self.user.username, self.coupon.code)

    @classmethod
    def add_coupon_redemption(cls, user, coupon, order_amount):
        """
        add coupon info into coupon_redemption model
        """

        if not Coupon.objects.filter(code=coupon, gender=user.profile.gender).exists():
            return "Coupon code does not exist."

        coupon = Coupon.objects.get(code=coupon)

        if (
            timezone.now() > coupon.start_date
            and timezone.now() < coupon.expiration_date
        ):
            if coupon.number_of_uses > 0:
                if len(cls.objects.filter(user=user, coupon=coupon)) < coupon.per_user_limit:
                    if coupon.discount_type == "percentage":
                        discount_amout = (order_amount * coupon.discount) / 100
                        amount = order_amount - discount_amout
                        # Check Birthdate
                        if timezone.now().date().strftime("%m/%d") == user.profile.date_of_birth.strftime("%m/%d"):
                            amount = amount - (amount * 10) / 100

                        if coupon.max_discount_amout < amount:
                            amount = order_amount - coupon.max_discount_amout
                    else:
                        amount = order_amount - coupon.discount
                    coupon.number_of_uses = coupon.number_of_uses - 1
                    coupon.save()
                    cls.objects.create(
                        user=user,
                        coupon=coupon,
                        order_amount=order_amount,
                        actual_price=amount,
                    )
                    return "{username} is successfully applied this {coupon_code} coupon.".format(
                        username=user.username, coupon_code=coupon.code
                    )
                else:
                    return "User reach max limit used"
            else:
                return "Coupon code max limit used."
        else:
            return "Coupon code expiried or not activate yet."


    @property
    def discount_amout(self):
        """
        return coupon gender
        """
        return self.order_amount - self.actual_price

forms.py
from django import forms

from .models import *


class CouponForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Coupon
        fields = "__all__"

views.py
import datetime

from django.shortcuts import render

from django.http import HttpResponse

from .models import *

from .forms import *


from django.shortcuts import redirect, render, reverse


def index(request):
    return HttpResponse("Hello, Hd")


def get_all_codes(request):
    """
    Return all code with all details.
    """

    codes = Coupon.objects.all()

    return render(
        request=request, template_name="promocode/codes.html", context={"codes": codes}
    )


def get_all_redemptions(request):
    """
    Return all code with all details.
    """

    codes = CouponRedemption.objects.all()

    return render(
        request=request,
        template_name="promocode/redemptions.html",
        context={"codes": codes},
    )


def add_new_code(request):
    """
    Add new Code form.
    """
    context = {}
    context["form"] = CouponForm()

    if request.method == "POST":

        form = CouponForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("get_all_codes"))
        else:
            context["form"] = form
            return render(request, "promocode/new_code.html", context)

    return render(request, "promocode/new_code.html", context)


def get_user_data(request):
    """
    Add User Details View.
    """
    context = {}

    if request.POST:
        data = request.POST
        user_id = data.get("user_id")
        birthdate = data.get("birthdate")
        gender = data.get("gender")
        order_amount = data.get("order_amount")
        order_code = data.get("order_code")

        try:
            if User.objects.filter(id=user_id).exists():
                user = User.objects.get(id=user_id)
                profile, created = UserProfile.objects.get_or_create(user=user)
                profile.date_of_birth = datetime.datetime.strptime(birthdate, "%m/%d/%Y")
                profile.gender = gender
                profile.save()
                if not int(order_amount) in range(100, 1500000):
                    context["msg"] = "Order amount must be  between 100 to 1500001"
                    return render(request, "promocode/user_data.html", context)
                redemption_msg = CouponRedemption.add_coupon_redemption(
                    user, order_code, int(order_amount)
                )
                context["msg"] = redemption_msg
                return render(request, "promocode/user_data.html", context)
            else:
                context["msg"] = "User ID does not exist."
                return render(request, "promocode/user_data.html", context)    
        except Exception as e:
            context["msg"] = e.__str__()
            return render(request, "promocode/user_data.html", context)

    return render(request, "promocode/user_data.html", context)

templates/promocode/codes.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2 style="text-align: center;">Coupon Codes</h2>
<h2 style="text-align: right;">
<a href="/add_new_code">
Add Coupon
</a>
</h2>

<table>
  <tr>
    <th>Code</th>
    
    <th>Gender</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Discount</th>
    <th>Max Discount Amout</th>
    <th>Counter</th>
    <th>is_active</th>
  </tr>
  	{% for code in codes %}
  	
  	<tr>
  		
    	<td>{{code.code}}</td>
    	<td>{{code.display_gender}}</td>
    	<td>{{code.start_date}}</td>
    	<td>{{code.expiration_date}}</td>
    	<td>{{code.discount}}</td>
    	<td>{{code.max_discount_amout}}</td>
    	<td>{{code.counter}}</td>
    	<td>{{code.is_active}}</td>
  	</tr>
    {% endfor %}
</table>

</body>
</html>

templates/promocode/new_code.html
<!DOCTYPE html>
<html>
<body>

<h2 style="text-align: center;">Add New Coupon Code</h2>

<form action = "" method = "post" style="text-align: -webkit-center;">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#id_start_date" ).datepicker();
    $( "#id_expiration_date" ).datepicker();
  } );
  </script>

</body>
</html>

templates/promocode/redemptions.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2 style="text-align: center;">Coupon Redemptions</h2>

<table>
  <tr>
    <th>Usename</th>
    <th>Date of Birth</th>
    <th>Gender</th>
    <th>Code</th>
    <th>Order Total Price</th>
    <th>Discount Price</th>
    <th>Order Actual Value (After Discount Applied)</th>
  </tr>
  	{% for code in codes %}
	  	<tr>
	    	<td>{{code.user.username}}</td>
	    	<td>{{code.user.profile.date_of_birth}}</td>
	    	<td>
	    		{% if code.user.profile.gender == 'm' %}
	    			Male
	    		{% else %}
	    			Female
	    		{% endif %}
	    	</td>
	    	<td>{{code.coupon.code}}</td>
	    	<td>{{code.order_amount}}</td>
	    	<td>{{code.discount_amout}}</td>
	    	<td>{{code.actual_price}}</td>
	  	</tr>
    {% endfor %}
</table>

</body>
</html>

templates/promocode/user_data.html
<!DOCTYPE html>    
<html>    
<head>    
<meta name="viewport" content="width=device-width, initial-scale=1">    
<style>    
* {    
  box-sizing: border-box;    
}    
    
input[type=text], select, textarea {    
  width: 100%;    
  padding: 12px;    
  border: 1px solid rgb(70, 68, 68);    
  border-radius: 4px;    
  resize: vertical;    
}    
input[type=email], select, textarea {    
  width: 100%;    
  padding: 12px;    
  border: 1px solid rgb(70, 68, 68);    
  border-radius: 4px;    
  resize: vertical;    
}    
    
label {    
  padding: 12px 12px 12px 0;    
  display: inline-block;    
}    
    
input[type=submit] {    
  background-color: rgb(37, 116, 161);    
  color: white;    
  padding: 12px 20px;    
  border: none;    
  border-radius: 4px;    
  cursor: pointer;    
  float: right;    
}    
    
input[type=submit]:hover {    
  background-color: #45a049;    
}    
    
.container {    
  border-radius: 5px;    
  background-color: #f2f2f2;    
  padding: 20px;    
}    
    
.col-25 {    
  float: left;    
  width: 25%;    
  margin-top: 6px;    
}    
    
.col-75 {    
  float: left;    
  width: 75%;    
  margin-top: 6px;    
}    
    
/* Clear floats after the columns */    
.row:after {    
  content: "";    
  display: table;    
  clear: both;    
}    
    
/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */    
</style>    
</head>    
<body>    
<h2 style="text-align:center;">Order Data</h2>    
<div class="container">    
  
  <form action = "" method = "post" style="text-align: -webkit-center;">
    {% csrf_token %}
    <div class="row">    
      <div class="col-25">    
        <label for="user_id">User ID</label>    
      </div>    
      <div class="col-75">    
        <input type="text" id="user_id" name="user_id" placeholder="Enter user id..">    
      </div>    
    </div>    
    <div class="row">    
      <div class="col-25">    
        <label for="birthdate">Birthdate</label>    
      </div>    
      <div class="col-75">    
        <input type="text" id="birthdate" name="birthdate" placeholder="Your birthdate..">    
      </div>    
    </div>    
  
    <div class="row">    
      <div class="col-25">    
        <label for="gender">Gender</label>    
      </div>    
      <div class="col-75">    
        <select id="gender" name="gender">      
          <option value="m">Male</option>    
          <option value="f">Female</option>    
        </select>    
      </div>    
    </div>    

    <div class="row">    
        <div class="col-25">    
          <label for="order_amount">Order Amount</label>    
        </div>    
        <div class="col-75">    
          <input type="text" id="order_amount" name="order_amount" placeholder="Enter Order Amount..">    
        </div>    
      </div>  

      <div class="row">    
        <div class="col-25">    
          <label for="order_code">Promo Code</label>    
        </div>    
        <div class="col-75">    
          <input type="text" id="order_code" name="order_code" placeholder="Enter Code..">    
        </div>    
      </div>  
    
    <div class="row">  
    	<p style="text-align: right;">
    	{% if msg %}
    		{{msg}}  
    	{% endif %}
    	</p>
      <input type="submit" value="Submit">    
    </div>    
  </form>    
</div>    

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#birthdate" ).datepicker();
  } );
  </script>

</body>    
</html>    